apiVersion: v1
kind: Service
metadata:
  name: klinik
  namespace: klinik
  labels:
    app: klinik
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 3000
    protocol: TCP
  selector:
    app: klinik
